### ISSUE TITLE
Star Trek TOS Color Palette

### ISSUE THREAD

**Issue by road2stat** [road2stat/ggsci#2]
Request from @dcgerard:
http://memory-alpha.wikia.com/wiki/Starfleet_uniform_(mid_2260s-early_2270s)

such as
http://starfleet1701st.yuku.com/topic/432/Uniform-Colours-by-Pantone-Reference
http://www.color-hex.com/color-palette/6450

**Comment by road2stat** [comment]
This should be solved by https://github.com/road2stat/ggsci/releases/tag/v2.4. @dcgerard

Though it might not be totally TOS-based as we try to make the colors work in harmony, as a color palette.

**Comment by dcgerard** [comment]
Thanks @road2stat!
