### ISSUE TITLE
Update problem

### ISSUE THREAD

**Issue by Tyelcie** [road2stat/ggsci#3]
Hi, I noticed your ggsci package have been updated to v2.7, however when I install it is till 2.4, and can't be updated. Do you have any solutions? Thanks in advance!

**Comment by road2stat** [comment]
Hi @Tyelcie , - please try install the latest stable version from CRAN with this:
```r
install.packages("ggsci", repos = "https://cran.rstudio.com")
```

**Comment by Tyelcie** [comment]
It worked! Thank you! Now I'd like to introduce it to my community^_^

**Comment by road2stat** [comment]
-- that's great! Happy to see that the issue is solved. 👍
