### ISSUE TITLE
Other Hallmarks of Cancer colors

### ISSUE THREAD

**Issue by jhrcook** [road2stat/ggsci#6]
So it turns out that COSMIC used different shades of the same colors for the Hallmarks of Cancer than in Weinberg's "Hallmarks of cancer: the next generation" paper. I would like to add Weinberg's (they are lighter shades and thus easier to use in plots), but am not sure where. Do you think this is a worthwhile addition and, if so, where would you like me to add them (in the `COSMIC` palette or a new palette)?

Thanks,
Josh Cook

**Comment by road2stat** [comment]
@jhrcook -please check this out: https://nanx.me/ggsci/reference/pal_uchicago.html. It is preferable to have them as separate options under a single palette, and (if necessary) show them all in the code example, readme, and vignette.

**Comment by jhrcook** [comment]
Great idea! Will do. 

- Josh Cook

**Comment by road2stat** [comment]
Solved by https://github.com/road2stat/ggsci/pull/7.
